### PR TITLE
Chapter 1 exercise solutions in jq

### PR DESCRIPTION
**Pull request by sshine**

### CODE REVIEW

**Comment by barrymoo** [comment]
@sshine Thanks for participating yesterday! It was a bit hectic, but I think we will figure it out as we go.

Regarding the PR, I am going to ask the meetup if we want to accept outside PRs. The original plan was to only include code from meetup members.

**Comment by barrymoo** [comment]
> How much is it to join? I mean to become a "member"?

We are actively discussing if we want to make the book club more open. Stay tuned.

**Comment by joelmccracken** [comment]
It kinda blows my mind that these exercises are done in jq

**Comment by barrymoo** [comment]
@sshine I just merged #8. See https://github.com/barrymoo/ctfp-book-club#guidelines-for-participation.

This PR follows the guidelines and I will simply merge it.

**Pull request merged**
