### PR TITLE
Chapter 3

### PR DESCRIPTION
**Pull request by mwm126**
Didn't get memoization working! Alas

### CODE REVIEW

**Comment by barrymoo** [comment]
Would you like me to merge these @mwm126? Or, did you want to play with the memoization stuff first?

**Comment by mwm126** [comment]
I'll play with memoization a bit more; would be fun to get it working

**Comment by barrymoo** [comment]
For sure! Just tag me when ready.

**Comment by mwm126** [comment]
@barrymoo please merge for Chapter 3!  (I never got around to the chapter 2 memoization, alas)

**Pull request merged**
